name: CI Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dummy build step
        run: echo "Build step would go here"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy application
        run: echo "Deploying application..."
